version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: axum_mysql
    env_file:
      - ./.env
    ports:
      - '3307:3306'
    volumes:
      - axum_mysql_mysqlDb:/var/lib/mysql
volumes:
  axum_mysql_mysqlDb: